version: 2

jobs:
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - restore_cache:
          key: module-cache-{{ checksum "go.mod" }}
      - run:
          name: Check dependencies
          command: make deps
      - run:
          name: Test with coverage
          command: make test-cover
      - save_cache:
          key: module-cache-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod/cache/download/
  lint:
    docker:
      - image: golangci/golangci-lint:v1.49
    steps:
      - checkout
      - restore_cache:
          key: module-cache-{{ checksum "go.mod" }}
      - run:
          name: Check dependencies
          command: make deps
      - run:
          name: Lint
          command: make lint

workflows:
  version: 2
  test_and_lint:
    jobs:
      - test
      - lint
