debug = true
server_host = "127.0.0.1"
api_host = "example.org"
server_port = "8080"
cache_limit = 10000
cache_ttl = "10m"
github_token = "YOUR_TOKEN"

[db]
path = "./bolt.db"
timeout = "1s"

[endpoint]
download = "/download"
list = "/list"
rss = "/rss"
