api_host = "example.org"
server_host = "127.0.0.1"
server_port = "8080"
http_timeout = "3s"

[db]
path = "./bolt.db"
timeout = "1s"

[endpoint]
download = "/download"
list = "/list"
rss = "/rss/{arch}.atom"

[github]
token = "YOUR_TOKEN"
watch_interval = "1m"
